This is an internal working file generated by the Source Browser.
12:00 26s
D:\Project\TRIO_MD\3.F_W\TRIO_MD_appl_stm207_20141103_Filter\STM32F2xx_StdPeriph_Driver_v1212\src\stm32f0xx_core.c
D:\Project\TRIO_MD\3.F_W\TRIO_MD_appl_stm207_20141103_Filter\STM32F2xx_StdPeriph_Driver_v1212\src\stm32f0xx_core.c
-D
NDEBUG
-lC
D:\Project\TRIO_MD\3.F_W\TRIO_MD_appl_stm207_20141103_Filter\STM32F2xx_StdPeriph_Driver_v1212\ewarm\sout\
-o
D:\Project\TRIO_MD\3.F_W\TRIO_MD_appl_stm207_20141103_Filter\STM32F2xx_StdPeriph_Driver_v1212\ewarm\sout\
--endian=little
--cpu=Cortex-M3
-e
--fpu=None
--dlib_config
C:\Program Files\IAR Systems\Embedded Workbench 6.0\arm\INC\c\DLib_Config_Normal.h
-I
D:\Project\TRIO_MD\3.F_W\TRIO_MD_appl_stm207_20141103_Filter\STM32F2xx_StdPeriph_Driver_v1212\ewarm\..\
-I
D:\Project\TRIO_MD\3.F_W\TRIO_MD_appl_stm207_20141103_Filter\STM32F2xx_StdPeriph_Driver_v1212\ewarm\..\inc\
-I
D:\Project\TRIO_MD\3.F_W\TRIO_MD_appl_stm207_20141103_Filter\STM32F2xx_StdPeriph_Driver_v1212\ewarm\..\..\uC-CPU\
-I
D:\Project\TRIO_MD\3.F_W\TRIO_MD_appl_stm207_20141103_Filter\STM32F2xx_StdPeriph_Driver_v1212\ewarm\..\..\uC-LIB\
-I
D:\Project\TRIO_MD\3.F_W\TRIO_MD_appl_stm207_20141103_Filter\STM32F2xx_StdPeriph_Driver_v1212\ewarm\..\..\uCOS-II\Ports\
-I
D:\Project\TRIO_MD\3.F_W\TRIO_MD_appl_stm207_20141103_Filter\STM32F2xx_StdPeriph_Driver_v1212\ewarm\..\..\uCOS-II\Source\
-Oh
